### ISSUE TITLE
Resource Category Post operation throws a time period error

### ISSUE THREAD

**Issue by javedishere** [digitel/resource-catalog-service#2]
The issue occurs for "ValidFor", same tags for PATCH operation work properly.

Request
 {
 
        "name": "Rnew",
        "description": "This category will contain the catalog and the sub catageries will contain all the resource candidates",
        "lastUpdate": "2018-04-24T14:56",
        "lifecycleStatus": "In-Design",
        "validFor": {
            "startDateTime": "2018-08-24T00:00",
            "endDateTime": "2018-03-25T00:00"
        },
        "version": "1.0",
        "isRoot": true,
       
        "@type": "ResourceCategory",
        "@baseType": "Category"
    }

Response

{
    "timestamp": "2018-04-24T20:39:33.441+0000",
    "status": "400",
    "error": "Bad Request",
    "message": " Field validFor -> {org.tmf.openapi.catlog.validation.date.timeperiod} ",
    "path": "uri=/catalogManagement/resourceCategory"
}

**Comment by tanmay14** [comment]
![image](https://user-images.githubusercontent.com/26224816/39227852-8907f29a-4878-11e8-9433-2f30dce02103.png)

Its created now--> Validation error for tag ValidFor as it expects data in Date format and we're parsing it as a String.
